@startuml

rectangle 流量来源 {
 头条等第三方APP --> (投放落地页)
 微信朋友圈及KOL文章 --> (投放落地页)
 云课堂APP域内 --> (投放落地页)
}
rectangle 微信域内 {
 投放落地页 --> (微信营销助手)
 微信营销助手 --> (小程序训练营)
}
rectangle 云课堂域内 {
 小程序训练营 --> (高价课)
}
@enduml