@startuml
  title 用户拉新到付费路径
  actor 新用户
  KOL微信文章 -> KOL微信文章:广告投放
  头条或第三方APP -> 头条或第三方APP:广告投放
  微信朋友圈 -> 微信朋友圈:广告投放
  新用户 -> KOL微信文章:人工决策
  KOL微信文章 -> 微信小助手:直接投放小助手
  KOL微信文章 -> 云课堂服务号:投服务号关注
  KOL微信文章 -> 投放落地页:直接投放落地页
  group 诺曼底投放的职责
  新用户 -> 微信朋友圈:基于ocpx数据精确定位广告目标用户
  微信朋友圈 -> 云课堂服务号:投服务号关注
  云课堂服务号 -> 投放落地页:消息推送
  微信朋友圈 -> 投放落地页:直接投放落地页
  新用户 -> 头条或第三方APP:基于ocpx数据精确定位广告目标用户
  头条或第三方APP -> 投放落地页:直接投放落地页
  投放落地页 -> 支付中间页:手机注册登录一体化、直接唤起微信支付
  支付中间页 -> 支付中间页:切换支付方式
  支付中间页 -> 领取成功页:支付完成自动重定向
  投放落地页 -> 领取成功页:自动微信登录，直接唤起微信支付
  领取成功页 -> 领取成功页:ocpx上报，转化成功
  end
  领取成功页 -> 微信小助手:扫码
  微信小助手 -> 微信学习群:微信营销
  微信学习群 -> 微信小程序:强调学习体验，增加购买欲望
  微信小程序 -> 高价微专业正课:达到真正的营收目的
@enduml