@startuml
note right of 投放页: 微信中
投放页 --> 投放页 : 通过url特殊标识launchType=mp和user_action_set_id进入该投放逻辑
投放页 --> 投放页 : 微信广告给页面url带上gdt_vid
投放页 -> 微信支付 : 当前页面唤起微信支付
微信支付 -> 投放页 : 支付完成后进行上报打点
投放页 -> 投放页: 打点接口
投放页 -> 支付成功页 : 打点成功后进行领取页重定向
投放页 -> 支付成功页 : 打点失败后进行领取页重定向
@enduml