@startuml
note right of 投放页: 微信中
投放页 --> 投放页 : 登录/注册，setCookie
投放页 -> 中间页 : 微信中默认微信支付成功(直接绕过中间页)
中间页 -> 成功页 : (直接绕过中间页)支付成功页面自动跳转
投放页 -> 投放页 : 微信中默认微信支付失败，微信中只有微信支付流程

note right of 投放页: 浏览器中
投放页 --> 投放页 : 登录/注册，setCookie
投放页 -> 唤起微信app支付 : 默认微信支付
唤起微信app支付 -> 成功页 :（支付成功）
唤起微信app支付 -> 中间页 :（支付失败）
中间页 --> 浏览器唤起支付宝支付 : 切换支付宝支付
浏览器唤起支付宝支付 --> 中间页: 支付跳转（无论成功失败）
中间页 --> 成功页: 支付成功页面自动跳转

note right of 投放页: APP中
投放页 --> 投放页 : 登录/注册，setCookie
投放页 -> 唤起微信app支付 : 默认微信支付（无论结果）
唤起微信app支付 -> 浏览器支付中间页 : 无论支付状态
浏览器支付中间页 -> 浏览器支付成功页: 支付成功页面自动跳转
浏览器支付中间页 --> 浏览器唤起支付宝支付 : 切换支付宝支付
浏览器唤起支付宝支付 --> 浏览器支付中间页: 支付跳转（无论成功失败）
浏览器支付中间页 --> 浏览器支付成功页 : 支付成功页面自动跳转
@enduml