@startuml

node "可视化搭建系统" {
      [组装拼接打包]
  [存储元数据]
}

node "用户访问前台系统" {
  [用户访问页面]
}


node "模块库" {
  [云课堂模块包]
  [中M模块包]
  [卡搭模块包]
  [元数据]
}

node "命令行工具" {
  [发布]
}

cloud {
  [存入html]
}


cloud {
  [取出html]
}


database "Mongodb" {
  frame "Page" {
    [页面1]
    [页面2]
    [页面3]
  }
}

[用户访问页面] <-- [取出html]
[取出html] <-- [页面1]

[组装拼接打包] -down-> [存入html]
[存入html] --> [页面1]

[元数据] -up-> [发布]
[发布] -right-> [存储元数据]
@enduml